---
#
# This is the primary playbook
# Site: Goldie
- hosts: Goldie
  gather_facts: no
  vars:
    site: Goldie
    project: GoldieNodes
    date: "{{ lookup('pipe','date +%Y.%m.%d.%H.%M') }}"

# Define All tasks
  tasks:
  - name: Running project {{project}} on {{site}} with Tags {{ansible_run_tags}} specified And tags {{ansible_skip_tags}} skipped
    delegate_to: 127.0.0.1
    run_once: true
    command: /bin/echo "Only running because of specified tag"
    changed_when: False
    tags:
        - always

  - name: Collect Facts
    setup:
    tags: ["never","facts"]

  - name: Common Role
    import_role:
        name: common

  - name: Flux Role
    import_role:
        name: flux

# Usage Task
  - debug: msg='You Must Specify a Tag to run this play Please see the Readme'
    run_once: true
